name: terraform-plan

on: [pull_request]

jobs:

        ejecucion-plan:
            runs-on: ubuntu-latest

            steps:

                - uses: actions/checkout@4
                - run: terraform plan
                - run: 
                    echo Se ha ejecutado un terraform plan